dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_esignet:
    enabled: true
    host: "esignet-postgres-postgresql.esignet"
    port: 5432
    su:
      user: postgres
      secret:
        name: esignet-postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet.git
    branch: develop
