apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-host
  namespace: esignet
  labels:
    app: postgres
data:
  POSTGRES_HOST: "postgres.esignet"
  POSTGRES_PORT: "5432"
  DB_USER: "esignetuser"
  DB_NAME: "mosip_esignet"
