## Uncomment required parms added with single '#' when needed.
#image:
#  registry: docker.io
#  repository: mosipdev/esignet
#  tag: develop

#extraEnvVars: |
#  - name: KEYCLOAK_EXTERNAL_URL
#    valueFrom:
#      configMapKeyRef:
#        name: keycloak-host
#        key: keycloak-external-url
#  - name: MOSIP_ESIGNET_CAPTCHA_SITE_KEY
#    valueFrom:
#      secretKeyRef:
#        name: esignet-captcha
#        key: esignet-captcha-site-key
#  - name: MOSIP_ESIGNET_CAPTCHA_MODULE_NAME
#    value: esignet
#  - name: IDA_AUTHENTICATOR_ENV
#    value: Staging
#  - name: REDIS_HOST
#    valueFrom:
#      configMapKeyRef:
#        name: redis-config
#        key: redis-host
#  - name: REDIS_PORT
#    valueFrom:
#      configMapKeyRef:
#        name: redis-config
#        key: redis-port
#  - name: REDIS_PASSWORD
#    valueFrom:
#      secretKeyRef:
#        name: redis
#        key: redis-password
#  - name: DATABASE_HOST
#    valueFrom:
#      configMapKeyRef:
#        name: postgres-config
#        key: database-host
#  - name: DATABASE_PORT
#    valueFrom:
#      configMapKeyRef:
#        name: postgres-config
#        key: database-port
#  - name: DATABASE_NAME
#    valueFrom:
#      configMapKeyRef:
#        name: postgres-config
#        key: database-name
#  - name: DATABASE_USERNAME
#    valueFrom:
#      configMapKeyRef:
#        name: postgres-config
#        key: database-username
#  - name: DB_DBUSER_PASSWORD
#    valueFrom:
#      secretKeyRef:
#        name: db-common-secrets
#        key: db-dbuser-password
#  - name: SOFTHSM_ESIGNET_SECURITY_PIN
#    valueFrom:
#      secretKeyRef:
#        name: esignet-softhsm
#        key: security-pin
#  - name: MOSIP_ESIGNET_HOST
#    valueFrom:
#      configMapKeyRef:
#        name: esignet-global
#        key: mosip-esignet-host
#  - name: MOSIP_SIGNUP_HOST
#    valueFrom:
#      configMapKeyRef:
#        name: esignet-global
#        key: mosip-signup-host
#  - name: MOSIP_IDA_CLIENT_SECRET
#    valueFrom:
#      secretKeyRef:
#        name: keycloak-client-secrets
#        key: mosip_ida_client_secret
#  - name: MOSIP_ESIGNET_MISP_KEY
#    valueFrom:
#      secretKeyRef:
#        name: esignet-misp-onboarder-key
#        key: mosip-esignet-misp-key
#extraEnvVarsCM:
#  - esignet-softhsm-share

#extraEnvVarsSecret: []

#istio:
#  enabled: true
#  gateways:
#    - istio-system/public
#    - istio-system/internal
#  prefix: /v1/esignet/

#enable_insecure: false
#springConfigNameEnv:
#activeProfileEnv:
#pluginNameEnv: esignet-mock-plugin.jar
#pluginUrlEnv:
