apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: esignet-postgres
spec:
  hosts:
    - "*"
  gateways:
  - postgres
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: esignet-postgres-postgresql
        port:
          number: 5432
    

